//! Sandboxed Rhai template rendering for the Claude Code status line.
//!
//! The status line is driven by `local-proxy statusline`, which passes a
//! session id and a template; this module evaluates the template against the
//! recorded stats. The template is a **Rhai** script, evaluated with no custom
//! plugins registered: Rhai is isolated by default (no file/network/host
//! access) so a template can do arithmetic, comparisons and boolean algebra
//! but is never arbitrary code.
//!
//! Params are bound as variables (numbers as `i64`/`f64`, everything else as
//! strings); the proxy decides which exist. A param that is absent / not
//! numeric binds to a `?` marker string so the template can format it. Any
//! parse/run failure is logged and a static fallback is returned, so the
//! status line keeps rendering even with a broken template.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// The static line printed when a template fails to parse or run.
const FALLBACK: &str = "statusline: erro";

/// The marker bound to params that have no data for this session.
pub const NO_DATA: &str = "?";

/// Build a sensible default template (a Rhai expression) from the params that
/// actually hold data, so an unconfigured user still gets a useful line.
///
/// Segments are added only when their param is present and not the [`NO_DATA`]
/// marker, and joined with `" · "`. An empty input yields a static line from
/// [`render`]. This powers the fallback when neither `--template` nor a config
/// `statusline:` template is set.
#[must_use]
pub fn default_template<S: std::hash::BuildHasher>(
    params: &std::collections::HashMap<String, String, S>,
) -> String {
    // Each value is a Rhai backtick-string interpolation fragment (`${var}`);
    // the segments are joined with " · " inside a single backtick string. The
    // result is a valid template for [`render`].
    let mut segs: Vec<String> = Vec::new();
    let has = |name: &str| params.get(name).is_some_and(|v| v != NO_DATA);
    if has("model") {
        segs.push("${model}".to_string());
    }
    if has("context_pct") {
        segs.push("${context_pct}% ctx".to_string());
    }
    if has("cost_session") {
        segs.push("${cost_session}".to_string());
    }
    if has("tokens_in") || has("tokens_out") {
        let tin = if has("tokens_in") {
            "${tokens_in}".to_string()
        } else {
            "?".to_string()
        };
        let tout = if has("tokens_out") {
            "${tokens_out}".to_string()
        } else {
            "?".to_string()
        };
        segs.push(format!("{tin} tok {tout}/"));
    }
    if segs.is_empty() {
        return "`local-proxy: sem dados`".to_string();
    }
    format!("`{}`", segs.join(" · "))
}

/// Render `template` (a Rhai script) with `params` bound as variables.
///
/// Every key in `params` is bound as a top-level variable of the same name.
/// Values that parse as `i64` or `f64` bind as numbers; anything else binds as
/// a string. Returns the rendered line, or [`FALLBACK`] (plus a logged error)
/// when the template cannot be parsed or evaluated.
#[must_use]
pub fn render<S: std::hash::BuildHasher>(
    template: &str,
    params: &HashMap<String, String, S>,
) -> String {
    let engine = rhai::Engine::new();
    let mut scope = rhai::Scope::new();
    for (name, value) in params {
        if let Ok(i) = value.parse::<i64>() {
            scope.push(name.as_str(), i);
        } else if let Ok(f) = value.parse::<f64>() {
            scope.push(name.as_str(), f);
        } else {
            scope.push(name.as_str(), value.clone());
        }
    }
    match engine.eval_with_scope::<rhai::Dynamic>(&mut scope, template) {
        Ok(out) => out.to_string(),
        Err(e) => {
            tracing::warn!(
                target: crate::LOG_TARGET,
                error = %e,
                template = %template,
                "status line template falhou; usando fallback"
            );
            FALLBACK.to_string()
        }
    }
}

// ---------------------------------------------------------------------------
// setup — write the status line script + register it in Claude's settings.json
// ---------------------------------------------------------------------------

/// Windows status-line script, embedded in the binary (no sidecar files).
///
/// Reads the status-line JSON from stdin, passes `session_id` and friends to
/// `local-proxy statusline`, and prints the rendered line.
pub const SCRIPT_WINDOWS: &str = r#"# Claude Code status line script (PowerShell).
# Generated by `local-proxy statusline setup`. Reads the status-line JSON from
# stdin, extracts the session id, and asks local-proxy to render the status
# line for that session.

param(
  [string]$Template = ""
)

# Note: `$input` is a reserved automatic variable in PowerShell, so the raw
# status-line JSON is read into `$raw` instead.
$raw = [Console]::In.ReadToEnd()

$session = ""
if ($raw -match '"session_id"\s*:\s*"([^"]*)"') { $session = $Matches[1] }
$model = ""
if ($raw -match '"(display_name|model)"\s*:\s*"([^"]*)"') { $model = $Matches[2] }
$ctx = ""
if ($raw -match '"used_percentage"\s*:\s*([0-9.]*)') { $ctx = $Matches[1] }

$args = @()
if ($session) { $args += "--session", $session }
if ($model)   { $args += "--model", $model }
if ($ctx)     { $args += "--context-pct", $ctx }
if ($Template){ $args += "--template", $Template }

& local-proxy statusline @args
"#;

/// POSIX status-line script, embedded in the binary (no sidecar files).
///
/// Reads the status-line JSON from stdin, passes `session_id` and friends to
/// `local-proxy statusline`, and prints the rendered line.
pub const SCRIPT_UNIX: &str = r#"#!/usr/bin/env bash
# Claude Code status line script.
# Generated by `local-proxy statusline setup`. Reads the status-line JSON from
# stdin, extracts the session id, and asks local-proxy to render the status
# line for that session.

set -euo pipefail

TPL=""            # optional: --template "..."
while [ "$#" -gt 0 ]; do
  case "$1" in
    --template) TPL="$2"; shift 2;;
    *) shift;;
  esac
done

# Read the status line JSON from stdin.
INPUT="$(cat 2>/dev/null || true)"

SESSION="$(printf '%s' "$INPUT" | sed -n 's/.*"session_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
MODEL="$(printf '%s' "$INPUT" | sed -n 's/.*"\(display_name\|model\)"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\2/p' | head -n1)"
CTX="$(printf '%s' "$INPUT" | sed -n 's/.*"used_percentage"[[:space:]]*:[[:space:]]*\([0-9.]*\).*/\1/p' | head -n1)"

ARGS=()
[ -n "$SESSION" ] && ARGS+=(--session "$SESSION")
[ -n "$MODEL" ]   && ARGS+=(--model "$MODEL")
[ -n "$CTX" ]     && ARGS+=(--context-pct "$CTX")
[ -n "$TPL" ]     && ARGS+=(--template "$TPL")

exec local-proxy statusline "${ARGS[@]}"
"#;

/// Filename of the Windows status-line script inside the config dir.
#[must_use]
pub const fn script_filename_windows() -> &'static str {
    "statusline.ps1"
}

/// Filename of the POSIX status-line script inside the config dir.
#[must_use]
pub const fn script_filename_unix() -> &'static str {
    "statusline.sh"
}

/// Path of the status-line script for the current platform in `config_dir`.
#[must_use]
pub fn script_path(config_dir: &Path) -> PathBuf {
    let name = if cfg!(windows) {
        script_filename_windows()
    } else {
        script_filename_unix()
    };
    config_dir.join(name)
}

/// JSON fragment mapping `statusLine` to a `type: command` run of `script`,
/// ready to be merged into a Claude `settings.json` or printed as a snippet.
#[must_use]
pub fn settings_statusline_command(script: &Path) -> String {
    let cmd = script.display().to_string();
    format!(r#"{{"statusLine":{{"type":"command","command":"{cmd}"}}}}"#)
}

/// Errors surfaced by [`setup`], formatted richly via miette.
#[derive(Debug, thiserror::Error, miette::Diagnostic)]
pub enum SetupError {
    /// The status-line script could not be written to the config dir.
    #[error("could not write the status line script to {path}: {source}")]
    #[diagnostic(
        code(statusline::setup::write),
        help("check the config dir is writable")
    )]
    WriteScript {
        /// Path of the script that could not be written.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// The script could not be made executable on POSIX.
    #[error("could not make the status line script executable at {path}: {source}")]
    #[diagnostic(code(statusline::setup::chmod), help("check the file permissions"))]
    Chmod {
        /// Path of the script that could not be made executable.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// Claude's `settings.json` could not be read or parsed.
    #[error("{message}")]
    #[diagnostic(
        code(statusline::setup::read),
        help("the file may be malformed JSON; edit or remove it and retry")
    )]
    Read {
        /// Human-readable description of the failure.
        message: String,
    },
    /// Claude's `settings.json` could not be written.
    #[error("could not write Claude settings to {path}: {source}")]
    #[diagnostic(
        code(statusline::setup::write_settings),
        help("check the file is writable")
    )]
    WriteSettings {
        /// Path of the settings file that could not be written.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
}

/// Return the Claude Code user `settings.json` path for the current platform.
///
/// Windows: `%USERPROFILE%\.claude\settings.json`; POSIX: `$HOME/.claude/settings.json`.
/// Falls back to `$HOME` when the platform-specific home var is unset. Returns
/// `None` when no home directory can be determined.
#[must_use]
pub fn claude_settings_path() -> Option<PathBuf> {
    let home = if cfg!(windows) {
        std::env::var_os("USERPROFILE").or_else(|| std::env::var_os("HOME"))
    } else {
        std::env::var_os("HOME").or_else(|| std::env::var_os("USERPROFILE"))
    }?;
    Some(PathBuf::from(home).join(".claude").join("settings.json"))
}

/// Merge a `statusLine` command into a Claude `settings.json`, preserving every
/// other setting, and return the new contents.
#[must_use]
pub fn merge_settings(current: &str, command: &str) -> String {
    let obj: serde_json::Value = if current.trim().is_empty() {
        serde_json::json!({})
    } else {
        serde_json::from_str(current).unwrap_or_else(|_| serde_json::json!({}))
    };
    let status = serde_json::json!({ "type": "command", "command": command });
    let mut map = obj.as_object().cloned().unwrap_or_default();
    map.insert("statusLine".to_string(), status);
    let out = serde_json::Value::Object(map);
    // Pretty-print with the same 2-space habit as Claude's own settings files.
    let pretty = serde_json::to_string_pretty(&out).unwrap_or_else(|_| out.to_string());
    format!("{pretty}\n")
}

/// Install the status line: write the script into `config_dir` and register it
/// in the user's Claude `settings.json`, preserving all other settings.
///
/// The settings file used is `--settings <path>` or the platform default.
/// Returns [`SetupPaths`] with the paths written. When a custom `settings`
/// path is supplied it is written even if it does not exist yet; otherwise the
/// write is skipped if the platform default settings file does not exist, so
/// setup never creates a `.claude` directory the user did not already have.
///
/// # Errors
///
/// Returns [`SetupError`] if the script or settings file cannot be written, or
/// the settings file cannot be read/parsed (except a genuinely absent default).
#[allow(clippy::needless_pass_by_value, clippy::result_large_err)]
pub fn setup(config_dir: &Path, settings: Option<PathBuf>) -> Result<SetupPaths, SetupError> {
    let script = script_path(config_dir);
    let is_windows = cfg!(windows);
    let contents = if is_windows {
        SCRIPT_WINDOWS
    } else {
        SCRIPT_UNIX
    };
    if let Some(parent) = script.parent() {
        std::fs::create_dir_all(parent).map_err(|source| SetupError::WriteScript {
            path: script.clone(),
            source,
        })?;
    }
    std::fs::write(&script, contents).map_err(|source| SetupError::WriteScript {
        path: script.clone(),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perm = std::fs::metadata(&script)
            .map_err(|source| SetupError::Chmod {
                path: script.clone(),
                source,
            })?
            .permissions();
        perm.set_mode(0o755);
        std::fs::set_permissions(&script, perm).map_err(|source| SetupError::Chmod {
            path: script.clone(),
            source,
        })?;
    }

    let settings_path = match settings {
        Some(p) => p,
        None => match claude_settings_path() {
            Some(p) if p.exists() => p,
            _ => {
                // No custom target and no default settings file yet: don't
                // fabricate a `.claude` directory. Leave the command printed for
                // the user to add manually.
                return Ok(SetupPaths {
                    script,
                    settings: None,
                });
            }
        },
    };

    let existing = if settings_path.exists() {
        std::fs::read_to_string(&settings_path).map_err(|source| SetupError::Read {
            message: format!(
                "could not read Claude settings at {}: {source}",
                settings_path.display()
            ),
        })?
    } else {
        String::new()
    };
    // Pass the bare script path as the command; `merge_settings` wraps it into
    // the `statusLine` object (the `settings_statusline_command` helper is only
    // used to print the manual wiring snippet when no settings file is found).
    let script_display = script.display().to_string();
    let next = merge_settings(&existing, &script_display);
    if let Some(parent) = settings_path.parent() {
        std::fs::create_dir_all(parent).map_err(|source| SetupError::WriteSettings {
            path: settings_path.clone(),
            source,
        })?;
    }
    std::fs::write(&settings_path, next).map_err(|source| SetupError::WriteSettings {
        path: settings_path.clone(),
        source,
    })?;

    Ok(SetupPaths {
        script,
        settings: Some(settings_path),
    })
}

/// Result of [`setup`]: the paths that were written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SetupPaths {
    /// Path of the status-line script written into the config dir.
    pub script: PathBuf,
    /// Path of the Claude `settings.json` updated, or `None` when no settings
    /// file was touched (custom target absent / default settings file absent).
    pub settings: Option<PathBuf>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn params(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect()
    }

    #[test]
    fn evaluates_arithmetic() {
        let p = params(&[("cost", "0.012"), ("tokens", "1500"), ("ctx", "42")]);
        let out = render("`$${cost} · ${tokens} tok · ${ctx}%`", &p);
        assert_eq!(out, "$0.012 · 1500 tok · 42%");
    }

    #[test]
    fn computes_from_params() {
        // cost expressed in cents with rounding
        let p = params(&[("cost", "0.0123"), ("mult", "100.0")]);
        let out = render("cost * mult", &p);
        assert_eq!(out, "1.23");
    }

    #[test]
    fn unknown_param_becomes_no_data_marker() {
        let p = params(&[("cost", "0.012"), ("requests", NO_DATA)]);
        // `requests` bound as the no-data marker string renders `?`
        let out = render("`${requests}`", &p);
        assert_eq!(out, NO_DATA);
    }

    #[test]
    fn division_and_format() {
        let p = params(&[("total", "90.0"), ("known", "3.0")]);
        let out = render("total / known", &p);
        assert_eq!(out, "30.0");
    }

    #[test]
    fn cost_absent_renders() {
        let p = params(&[("cost", NO_DATA)]);
        let out = render("`cost=${cost}`", &p);
        assert_eq!(out, "cost=?");
    }

    #[test]
    fn broken_template_falls_back() {
        let p = params(&[]);
        // a syntax error -> parser error -> fallback
        let out = render("this is (not valid", &p);
        assert_eq!(out, FALLBACK);
    }

    #[test]
    fn setup_merges_into_settings_and_writes_script() {
        let dir = tempfile::tempdir().expect("tempdir");
        let cfg = dir.path().join("cfg");
        let settings = dir.path().join("settings.json");
        std::fs::write(&settings, r#"{"theme":"dark"}"#).expect("write settings");

        let paths = super::setup(&cfg, Some(settings.clone())).expect("setup ok");

        let script = if cfg!(windows) {
            super::script_filename_windows()
        } else {
            super::script_filename_unix()
        };
        assert_eq!(paths.script, cfg.join(script));
        assert!(paths.script.exists());
        assert_eq!(paths.settings.as_deref(), Some(settings.as_path()));

        // the settings file now has the statusLine entry besides theme
        let contents = std::fs::read_to_string(&settings).expect("read settings back");
        let obj: serde_json::Value = serde_json::from_str(&contents).expect("valid json");
        assert_eq!(obj["theme"], "dark");
        assert_eq!(obj["statusLine"]["type"], "command");
        assert_eq!(
            obj["statusLine"]["command"],
            paths.script.display().to_string()
        );
    }

    #[test]
    fn merge_settings_preserves_other_keys() {
        let next = super::merge_settings(r#"{"apiKeyHelper":true}"#, "/x/statusline.ps1");
        let obj: serde_json::Value = serde_json::from_str(&next).expect("valid json");
        assert_eq!(obj["apiKeyHelper"], true);
        assert_eq!(obj["statusLine"]["command"], "/x/statusline.ps1");
    }

    #[test]
    fn merge_settings_defaults_to_empty_when_garbage() {
        let next = super::merge_settings("not json at all", "/x/st.sh");
        let obj: serde_json::Value = serde_json::from_str(&next).expect("valid json");
        assert_eq!(obj["statusLine"]["command"], "/x/st.sh");
    }

    #[test]
    fn claude_settings_path_resolves_under_home() {
        let _guard = crate::TEST_STATE_LOCK.lock().unwrap();
        let dir = tempfile::tempdir().expect("tempdir");
        let home = dir.path().join("home");
        // Point the platform-relevant home var at a fresh dir and verify the
        // platform default path resolves under `.claude/settings.json`.
        if cfg!(windows) {
            std::env::set_var("USERPROFILE", &home);
        } else {
            std::env::set_var("HOME", &home);
        }
        let p = super::claude_settings_path().expect("resolves");
        assert_eq!(p, home.join(".claude").join("settings.json"));
    }

    #[test]
    fn windows_script_does_not_use_reserved_input_var() {
        // `$input` is a reserved automatic variable in PowerShell: assigning to
        // it never holds the value, so the script would read empty stdin and
        // extract no session/model/context. The script must read into `$raw`.
        let script = super::SCRIPT_WINDOWS;
        assert!(script.contains("$raw = [Console]::In.ReadToEnd()"));
        assert!(!script.contains("$input = "), "must not assign to $input");
        // the JSON extraction reads from `$raw`, not the reserved variable
        assert!(!script.contains("if ($input -match"));
        assert!(script.contains("if ($raw -match"));
    }

    #[test]
    fn default_template_shows_available_params() {
        let p = params(&[
            ("model", "claude-x"),
            ("context_pct", "42"),
            ("cost_session", "0.012"),
            ("tokens_in", "1500"),
            ("tokens_out", "300"),
        ]);
        let tpl = super::default_template(&p);
        assert_eq!(
            tpl,
            "`${model} · ${context_pct}% ctx · ${cost_session} · ${tokens_in} tok ${tokens_out}/`"
        );
        // and rendering that template yields a present, readable line
        assert_eq!(
            super::render(&tpl, &p),
            "claude-x · 42% ctx · 0.012 · 1500 tok 300/"
        );
    }

    #[test]
    fn default_template_omits_missing_params() {
        // cost absent -> not included; tokens absent -> tokens segment shows ?
        let p = params(&[("model", "claude-x"), ("context_pct", "10")]);
        let tpl = super::default_template(&p);
        assert_eq!(tpl, "`${model} · ${context_pct}% ctx`");
        assert_eq!(super::render(&tpl, &p), "claude-x · 10% ctx");
    }

    #[test]
    fn default_template_no_data_falls_back() {
        let p = params(&[("model", NO_DATA), ("context_pct", NO_DATA)]);
        let tpl = super::default_template(&p);
        assert_eq!(tpl, "`local-proxy: sem dados`");
        assert_eq!(super::render(&tpl, &p), "local-proxy: sem dados");
    }
}
